### PR TITLE
Assignment 1 delivery!

### PR DESCRIPTION
**Pull request by efantinatti**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
A: Answered assignment questions!

## What did you learn from the changes you have made?
A: A lot of using specific libraries for fitting models with simple and multiple linear regressions.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
A: No.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
A: a lot of challenges.

## How were these changes tested?
A: Code execution and results on screen.

## A reference to a related issue in your repository (if applicable)
A: n/a

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by amanda-ng518 — APPROVED** [review]
A1: Q2 missing hypotheses statements

**Review by amanda-ng518 — CHANGES_REQUESTED** [review]
A1: Q2 missing hypotheses statements

**Comment by efantinatti** [comment]
Hi Amanda

I am not sure if I understand your revision.

This is what I have there:

[image: image.png]

**Review by amanda-ng518 — APPROVED** [review]
A1: reviewed

**Pull request closed without merging**
